config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # mount ActionCable.server => '/cable'
  root 'home#index'

  mount Sidekiq::Web => '/sidekiq' if defined?(Sidekiq) && defined?(Sidekiq::Web)

  if Rails.env.development?
    scope format: true, constraints: { format: /jpg|png|gif|PNG/ } do
      get '/*anything', to: proc { [404, {}, ['']] }, constraints: lambda { |request|
                                                                     !request.path_parameters[:anything].start_with?('rails/')
                                                                   }
    end
  end
  devise_for :users,
             path: '',
             path_names: { sign_in: 'login', sign_out: 'logout', edit: 'profile', sign_up: 'signup' },
             controllers: { registrations: 'users/registrations',
                            omniauth_callbacks: 'users/omniauth_callbacks' }

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  scope '/:locale' do
    devise_scope :user do
      get 'users', to: 'devise/sessions#new'
      get 'login', to: 'devise/sessions#new'
      get 'register', to: 'devise/registrations#new'
      get 'logout', to: 'devise/sessions#destroy'
      get 'users/carts', to: 'carts#index'
      get 'users/checkout_vnpay', to: 'checkouts#index'
      get 'users/checkout_vnpay/pay', to: 'checkouts#create'
    end
    get 'product_details/index'
    get 'product-details/:id', to: 'product_details#index'
    get 'category/:id', to: 'categories#categories'
    get 'contact', to: 'contact#index'
    post 'contact', to: 'contact#create'
    get 'brand/:id', to: 'brand#brands'
    get 'blog', to: 'blog#index'
    get 'blog_detail/:id', to: 'blog#blog_detail'
    get 'blog_category/:id', to: 'blog#blog_category'
    get 'users/orders', to: 'orders#index'
    get 'users/loves', to: 'loves#index'
    get 'users/history_product', to: 'product_view#index'
    get 'notification/:id', to: 'notification#index'
    get 'admin/system', to: 'notification#index'
  end
  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      get '/category', to: 'categories#index'
      post '/love', to: 'loves#index'
      post '/comment', to: 'loves#comment'
      post '/rate', to: 'loves#rate'
      post '/checkout', to: 'carts#checkout'
      post '/checkout_with_momo', to: 'carts#payment_momo'
      get '/checkout_success', to: 'carts#success'

      delete '/unlove', to: 'loves#unlove'
      post 'edit-comment', to: 'loves#edit_comment'
      post 'edit-comment-children', to: 'loves#edit_comment_children'
      delete 'delete-comment-children', to: 'loves#delete_comment_children'

      delete '/delete-comment', to: 'loves#delete_comment'
      post 'reply-comment', to: 'loves#reply_comment'
      post '/product', to: 'products#products_of_month'
      post '/search', to: 'products#search'
      post '/voucher', to: 'products#voucher'
      post '/delete_order', to: 'products#delete_order'
      post '/search_blog', to: 'blogs#search'
      get '/load_more_product', to: 'products#more_product'
      get '/load-more-comment', to: 'loves#more_comment'
      get '/quick-review', to: 'products#quick_review'
    end
  end
end

app/controllers/api/v1/blogs_controller.rb
# frozen_string_literal: true

module Api
  module V1
    class BlogsController < Api::V1::BaseController
      skip_before_action :require_jwt

      def search
        posts = if params[:search].present?
                  Post.where('title LIKE ?', "%#{params[:search]}%").limit(10)
                else
                  Post.newest.page(params[:page]).per(10)
                end
        render json: success_message('Successfully',
                                     { blogs: ActiveModelSerializers::SerializableResource.new(posts,
                                                                                               each_serializer: BlogSerializer) })
      end
    end
  end
end

app/controllers/blog_controller.rb
# frozen_string_literal: true

class BlogController < ApplicationController
  before_action :load_layout, only: %i[index blog_detail]

  def index; end

  def blog_detail
    env_http_forwarded = request.env['HTTP_X_FORWARDED_FOR']
    client_ip = if env_http_forwarded
                  env_http_forwarded.split(',').first
                else
                  request.remote_ip
                end
    id = params[:id].match(/\d+$/)[0].to_i
    post_view = ProductView.new(post_id: id, ip_post: client_ip, city: request.location&.city)
    p_view = ProductView.find_by(ip_post: client_ip, post_id: id)
    post_view.save(validate: false) unless p_view
    post = Post.find(id)
    # post_other = Post.where.not(id: id).where(category_post_id: post.category_post_id).order('RANDOM()').limit(10)
    post_other = Post.where.not(id: id).where(category_post_id: post.category_post_id).sample(10)

    @results = {
      post: post,
      post_other: post_other,
      notifications: @results[:notifications],
      categoies_post: @results[:categoies_post],
      best_view_post: @results[:best_view_post]
    }
  end

  def blog_category
    id = params[:id].match(/\d+$/)[0].to_i
    list_post = Post.where(category_post_id: id).newest.page(params[:page]).per(10)

    @results = {
      list_post: list_post,
      notifications: load_notification
    }
  end

  private

  def load_layout
    posts = Post.newest.page(params[:page]).per(10)
    categoies_post = CategoryPost.all
    product_views = ProductView.select(:post_id).where.not(post_id: nil).group(:post_id).order('post_id DESC')
    post_ids = product_views.size.values.sort.reverse.take(10).map { |item| product_views.size.key(item) }
    best_view_post = product_views.where(post_id: post_ids)
    @results = {
      categoies_post: categoies_post,
      posts: posts,
      notifications: load_notification,
      best_view_post: best_view_post
    }
  end

  def load_notification
    @notifications = Notification.newest.limit(5)
  end
end

app/views/blog/blog_category.html.erb
<section>
  <div class="container">
    <div class="row">
      <div class= "col-sm-1 "></div>
      <div class= "col-sm-11 " >
        <h2 class="title text-center">Category: <%= @results[:list_post].first&.category_post.name %></h2>
        <% @results[:list_post].each do |item| %>
          <a href="/<%=I18n.locale %>/blog_detail/<%= item.title.parameterize%>~<%=item.id %>" style="color: black">
            <article>
              <img src="<%= url_for(item.image) if item.image.attached? %>" alt="Image" class="list_post">
              <div class="text">
                <h4><%= item.title %></h4>
                <p>
                  <i class="fa fa-calendar"></i> <%= item.created_at.strftime("%d/%m/%Y") %>
                  <i class="fa fa-user"></i> <%= item.user.username %>
                </p>
                <p><%= item.content %></p>
                <a  class="btn btn-primary" href="/<%=I18n.locale %>/blog_detail/<%= item.title.parameterize%>~<%=item.id %>"><%= t("blogs.read_more") %></a>
              </div>
            </article>
          </a>
        <% end %>
        <div style="text-align: center">
          <%= paginate @results[:list_post], theme: 'twitter-bootstrap-4' %>
        </div>
      </div>
</section>

app/views/blog/blog_detail.html.erb
<section>
  <div class="container">
    <div class="row">
      <div class="col-sm-3">
        <div class="left-sidebar">
          <div class="brands_products">
            <h2>Category</h2>
            <%= render 'home/category_blog' %>
          </br>
          <h2>Post Best View</h2>
          <%= render 'home/best_view_blog' %>
        </div>
      </div>
    </div>
    <div class="col-sm-9">
      <div class="blog-post-area">
        <h2 class="title text-center"><%= @results[:post].title %></h2>
        <div class="single-blog-post">
          <div class="post-meta">
            <ul>
              <li><i class="fa fa-user"></i> <%=  @results[:post].user.username %></li>
              <li><i class="fa fa-calendar"></i> <%=  @results[:post].created_at.strftime("%d/%m/%Y") %></li>
              <li><i class="fa fa-eye"></i> <%= @results[:post].product_views.count %></li>
            </ul>
            <span>
              <i class="fa fa-star"></i>
              <i class="fa fa-star"></i>
              <i class="fa fa-star"></i>
              <i class="fa fa-star"></i>
              <i class="fa fa-star-half-o"></i>
            </span>
          </div>
          <a href="">
            <img src="<%= url_for( @results[:post].image) if  @results[:post].image.attached? %>" alt="">
          </a>
          <span style="word-wrap: break-word;"> <%=  @results[:post].body.body%></span>
          <div class="pager-area">
            <ul class="pager pull-right">
              <li><a href="<%= blog_path %>">Pre</a></li>
              <li><a href="#">Next</a></li>
            </ul>
          </div>
        </div>
      </div>
      <!--/blog-post-area-->
      <div class="rating-area">
        <ul class="ratings">
          <li class="rate-this">Rate this item:</li>
          <li>
            <i class="fa fa-star color"></i>
            <i class="fa fa-star color"></i>
            <i class="fa fa-star color"></i>
            <i class="fa fa-star color"></i>
            <i class="fa fa-star color"></i>
          </li>
          <li class="color">(5 votes)</li>
        </ul>
        <ul class="tag">
          <li>TAG: </li>
          <li><a class="color" href="#"> <%=  @results[:post].category_post.name %> </a></li>
        </ul>
      </div>
      <!--/rating-area-->
      <div class="socials-share">
        <a href=""><img src="images/blog/socials.png" alt=""></a>
      </div>
      <!--/socials-share-->
      <div class="media commnets">
        <a class="pull-left col-1" href="#" >
          <img class="media-object" src="<%= url_for( @results[:post].user.avatar) if  @results[:post].user.avatar.attached? %>" alt="">
        </a>
        <div class="media-body col-11" >
          <h4 class="media-heading">Author: <span style="color: #FE980F;"><%=  @results[:post].user.username %></span></h4>
          <p><%= @results[:post].user.profile %></p>
          <h4 class="media-heading">Facebook: <a href="https://www.facebook.com/thangneymar44/"><i class="fa fa-facebook"></i></a> </h4>
        </div>
      </div>
      <h2 class="title text-center"><%= t("blogs.other_post") %></h2>
      <div class="row">
        <div class="multiple-items" >
          <% @results[:post_other].each do |item| %>
            <a  href="/<%=I18n.locale %>/blog_detail/<%= item.title.parameterize%>~<%=item.id %>" class= "col-sm-3">
              <img style="width: 100%" src="<%= url_for(item.image) if item.image.attached? %>" alt="Image">
              <h5 class="title_post"> <%= item.title %> </h5>
            </a>
          <% end %>
        </div>
      </div>
    </div>
  </section>
  <style>
    .current{
    	width: 50px;
        height: 40px;
        text-align: center;
        line-height: 26px;
    }
    .title_post{
    	font-size: 16px;
        font-family: auto;
        text-align: center;
        color: black;
        font-weight: 700;
    }
  </style>
  <script>
    $('.multiple-items').slick({
    	slidesToShow: 2,
    	slidesToScroll: 2,
    	autoplay: true,
    	autoplaySpeed: 2000,
        prevArrow: false,
        nextArrow: false,
    });
  </script>
  <script>
    $(".in-search").css("display", "none");
  </script>

app/views/blog/index.html.erb
<section>
  <div class="container">
    <div class="row">
      <div class="col-sm-3">
        <div class="left-sidebar">
          <div class="brands_products">
            <h2><%= t("blogs.category")%></h2>
            <%= render 'home/category_blog' %>
          </br>
          <h2><%= t("blogs.post_best_view")%></h2>
          <%= render 'home/best_view_blog' %>
          <h2><%= t 'slide_bar.fanpage' %></h2>
          <%= render 'home/fanpage' %>
          <h2 style="margin-top: 10px"><%= t 'slide_bar.group' %></h2>
          <%= render 'home/group_facebook' %>
          <h2><%= t 'slide_bar.youtube' %></h2>
          <%= render 'home/youtube' %>
        </div>
      </div>
    </div>
    <div class= col-sm-9>
      <div class="search_box pull-right">
        <input class="in-search-blog" id="search-blog" data-autocomplete-source="<%= Post.order("title").map(&:title)%>" type="text" style="color: #000; font-weight: 700;" placeholder="<%= t 'blogs.search_post' %>">
      </div>
      <h2 class="title text-center" ><%= t("blogs.list_post") %></h2>
      <div class="list-post">
        <% @results[:posts].each do |item| %>
          <a href="/<%=I18n.locale %>/blog_detail/<%= item.title.parameterize%>~<%=item.id %>" style="color: black">
            <article>
              <img src="<%= url_for(item.image) if item.image.attached? %>" alt="Image" class="list_post">
              <div class="text">
                <h4><%= item.title %></h4>
                <p>
                  <i class="fa fa-calendar"></i> <%= item.created_at.strftime("%d/%m/%Y") %>
                  <i class="fa fa-user"></i> <%= item.user.username %>
                </p>
                <p><%= item.content %></p>
                <a  class="btn btn-primary" href="/<%=I18n.locale %>/blog_detail/<%= item.title.parameterize%>~<%=item.id %>"><%= t("blogs.read_more") %></a>
              </div>
            </article>
          </a>
        <% end %>
      </div>
      <div style="text-align: center" class="pagination-blog">
        <%= paginate @results[:posts], theme: 'twitter-bootstrap-4' %>
      </div>
    </div>
  </section>
  <div id="myModal" class="modal fade" role="dialog">
    <div class="modal-dialog">
      <!-- Modal content-->
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <!--         <h4 class="modal-title">Modal Header</h4> -->
        </div>
        <div class="modal-body text-center">
          <h1>📝Chia sẻ 200 Game Giảng Dạy Powerpoint Full Chủ đề VIP</h1>
          <%# <p style="font-size: 20px;font-weight: 700;">Edulive | Nền tảng dạy học trực tuyến toàn diện </p> %>
          <a href="https://www.facebook.com/groups/1011713702919105/posts/1231917210898752">
            <img src="https://i.ibb.co/89sKhHt/Screenshot-from-2022-09-02-11-11-56.png" alt="Italian Trulli" style="width: 100%;height: 100%;">
            <a class="pre-order-btn" href="https://www.facebook.com/groups/1011713702919105/posts/1231917210898752/" >NHẤN VÀO ĐỂ  XEM CHI TIẾT 200 GAME</a>
          </div>
        </a>
        <div class="modal-footer">
           👉 <a class="pre-order-btn" href="https://www.facebook.com/thangneymar44" >FB AD : Trần Hữu Thắng</a>
          <!--         <button type="button" class="btn btn-default" data-dismiss="modal">Close</button> -->
        </div>
      </div>
    </div>
  </div>
  <style>
    @media (max-width: 480px) {
    .in-search-blog {
        color: #000;
        font-weight: 700;
        margin-top: 22px;
        margin-bottom: 15px;
        position: absolute;
        left: 15px;
      }
    }
      .modal-body h1 {
      	 font-weight: 900;
      	 font-size: 1.3em;
      	 text-transform: uppercase;
         line-height: 4.3rem;
      }
       .modal-body a.pre-order-btn {
      	 color: #000;
      	 background-color: gold;
      	 border-radius: 1em;
      	 padding: 1em;
      	 display: block;
      	 margin: 2em auto;
      	 width: 50%;
      	 font-size: 1.25em;
      	 font-weight: 6600;
      }
       .modal-body a.pre-order-btn:hover {
      	 background-color: #000;
      	 text-decoration: none;
      	 color: gold;
      }
  </style>
  <script id="list-search-blog-template" type="text/x-handlebars-template">
    {{#if blogs }}
      {{#each blogs}}
           <a href="/<%=I18n.locale %>/blog_detail/{{title}}~{{id}}" style="color: black">
             <article>
               <img src="{{image_url}}" alt="Image" class="list_post">
               <div class="text">
                 <h4>{{title}}</h4>
                 <p>
                   <i class="fa fa-calendar"></i> {{created_at}}
                   <i class="fa fa-user"></i> {{username}}
                 </p>
                 <p> {{content}}</p>
                 <a  class="btn btn-primary" href="/<%=I18n.locale %>/blog_detail/{{title}}~{{id}}"><%= t("blogs.read_more") %></a>
               </div>
             </article>
           </a>
      {{/each}}
    {{else}}
    <h1 style="text-align: center;"> <%= t("messages.blog") %> "{{keyword}}"  </h1>
      <style>
       .pagination-blog
       {
         display: none;
       }
      </style>
     {{/if}}
  </script>
  <script>
    $(document).ready(function () {
        if (!sessionStorage.getItem('isModalOpen')) {
            $("#myModal").modal();
            sessionStorage.setItem('isModalOpen', true);
        }
    });
    $(".in-search").css("display", "none");
    $( function() {
      $( "#search-blog" ).autocomplete({
        maxResults: 5,
        minLength: 2,
        source:  function(request, response) {
        var results = $.ui.autocomplete.filter( $("#search-blog").data("autocomplete-source"), request.term);
        response(results.slice(0, this.options.maxResults));
        } ,
      });
    });
  </script>